In [1]:
import numpy as np

In [23]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
con_mayor5 = arr >5
con_mayor5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
arr[con_mayor5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [12]:
cond_menor4 = arr<4
cond_menor4

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [13]:
arr[cond_menor4]

array([1, 2, 3], dtype=int8)

In [16]:
arr[(arr>=3)&(arr<8)]

array([3, 4, 5, 6, 7], dtype=int8)

In [24]:
arr2 = arr.copy()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [25]:
arr2[arr2<8]=77
arr2

array([77, 77, 77, 77, 77, 77, 77,  8,  9, 10], dtype=int8)

In [32]:
arr2[arr2==77]

array([77, 77, 77, 77, 77, 77, 77], dtype=int8)