In [18]:
import numpy as np

In [19]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr_piece = arr[0:6]
arr_piece

array([0, 1, 2, 3, 4, 5])

In [21]:
arr_piece[:]=0
arr_piece

array([0, 0, 0, 0, 0, 0])

In [22]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])