In [2]:
import numpy as np

In [5]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [9]:
vector = np.array([1,2,3,4,5,6])
print(vector)
vector.ndim

[1 2 3 4 5 6]


1

In [11]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [16]:
tensor = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
print(tensor)
tensor.ndim

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]


4

In [20]:
vector2= np.array([1,2,3])
print(vector2)
vector2.ndim

[1 2 3]


1

In [37]:
vectorexpandido = np.expand_dims(vector2,axis=0)
print(vectorexpandido)
vectorexpandido.ndim

[[1 2 3]]


2

In [38]:
vectoreducido = np.squeeze(vectorexpandido,axis=0)
print(vectoreducido)
vectoreducido.ndim

[1 2 3]


1

Reto de clase,
Crear un tensor con al menos 5 dimensiones, Agregar y quitar dimensiones a gusto.

In [40]:
tensor1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor1)
tensor1.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [43]:
# Creando el tensor con 5 dimensiones explicitamente:
tensor2 = np.array([1,2,3,4,5,6,7,8,9],ndmin=5)
print(tensor2)
tensor2.ndim

[[[[[1 2 3 4 5 6 7 8 9]]]]]


5

In [44]:
#Tomando tensor 1 y ampliando dimensiones 
tensor3 = np.expand_dims(tensor1,axis=0)
print(tensor3)
tensor3.ndim

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


4

In [49]:
#Tomando Tensor 3 y disminuyendo 1 dimension:
tensor4 = np.squeeze(tensor3,axis=0)
print(tensor4)
tensor4.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3