In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[19, 17,  3, 16,  2],
       [ 1, 13, 17,  9, 11]])

In [4]:
matriz.max()
# si no se agrega ningun criterio nos devuelve el numero mayor dentro de la matriz

np.int64(19)

In [5]:
matriz.max(0)
# Si agregamos el valor 0 nos retorna el mayor de cada una de las columnas

array([19, 17, 17, 16, 11])

In [6]:
matriz.max(1)
# Si agregamos el valor 1 nos retorna el mayor de cada una de las filas

array([19, 17])

In [7]:
arr.argmax()
# Nos retorna el eje donde se encuentra el numero con el mayor valor.

np.int64(0)

In [8]:
arr.argmax(0)
# Nos retorna en que columna se encuentra el valor mayor

np.int64(0)

In [9]:
matriz.argmax(1)
# Solo funciona con estructuras matriciales.
# Nos retorna en que fila se encuentra el valor mayor

array([0, 2])

In [10]:
matriz.argmax(0)
# Solo funciona con estructuras matriciales.
# Nos retorna en que columna se encuentra el valor mayor

array([0, 0, 1, 0, 1])

ES MUY IMPORTANTE ENTENDER QUE NUMPY MANEJA LOS ARREGLOS DE OBJETOS MATRICES COMO COLUMNAS Y FILAS ES DECIR, CUANDO DEFINIMOS PARAMETROS FUNCIONAN DE LA SIGUIENTE MANERA
0 = COLUMNAS
1 = FILAS

LO DEFINIMOS AQUI PORQUE NORMALMENTE CUANDO SE REFIERE A MATRICES LO HACEMOS DICIENDO FILAS Y COLUMNAS Y ESTO PODRIA LLEGAR A CONFUNDIR SI NO SE OBSERVA.

In [11]:
matriz

array([[19, 17,  3, 16,  2],
       [ 1, 13, 17,  9, 11]])

In [12]:
arr
matriz

array([[19, 17,  3, 16,  2],
       [ 1, 13, 17,  9, 11]])

In [13]:
arr.argmin()

np.int64(5)

In [14]:
matriz.argmin(0)

array([1, 1, 0, 1, 0])

In [15]:
matriz.argmin(1)

array([4, 0])

In [16]:
matriz

array([[19, 17,  3, 16,  2],
       [ 1, 13, 17,  9, 11]])

In [17]:
np.ptp(matriz)

np.int64(18)

In [18]:
np.ptp(matriz,axis=0)
# Analiza la diferencia entre el punto maximo y minimo entre cada columna

array([18,  4, 14,  7,  9])

In [19]:
np.ptp(matriz,axis=1)
# Analiza la diferencia entre el punto maximo y minimo entre cada Fila

array([17, 16])

In [20]:
matriz

array([[19, 17,  3, 16,  2],
       [ 1, 13, 17,  9, 11]])

In [31]:
np.percentile(matriz,50)

np.float64(12.0)

In [24]:
np.median(matriz)


np.float64(12.0)

In [26]:
matriz.sort()
matriz
# Ordena el contenido de una arrange

array([[ 2,  3, 16, 17, 19],
       [ 1,  9, 11, 13, 17]])

In [27]:
arr.sort()
arr

array([ 1,  2,  3,  9, 11, 13, 16, 17, 17, 19])

In [28]:
enmedio = (11+13)/2
print(f'Esto es lo que hay en esta variable {enmedio}')

Esto es lo que hay en esta variable 12.0


In [33]:
np.median(matriz,1)

np.float64(12.0)

In [35]:
np.std(matriz)**2

np.float64(41.35999999999999)

In [37]:
np.var(matriz)

np.float64(41.36)

In [38]:
np.mean(arr)

np.float64(10.8)

In [39]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [56]:
b = np.array([5,6])
b

array([5, 6])

In [58]:
b=np.expand_dims(b,axis=0)

In [61]:
a.ndim
# b.ndim

2

In [62]:
# a.ndim
b.ndim

2

In [63]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [66]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])