In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,6))
arr

array([[9, 4, 2, 3, 1, 2],
       [6, 4, 4, 4, 1, 5],
       [2, 8, 2, 3, 8, 6]])

In [3]:
arr.shape

(3, 6)

In [4]:
tensor = np.array([1,2,3,4,5,6],ndmin=3)
tensor.shape

(1, 1, 6)

In [5]:
arr

array([[9, 4, 2, 3, 1, 2],
       [6, 4, 4, 4, 1, 5],
       [2, 8, 2, 3, 8, 6]])

In [6]:
arr.reshape(6,3)

array([[9, 4, 2],
       [3, 1, 2],
       [6, 4, 4],
       [4, 1, 5],
       [2, 8, 2],
       [3, 8, 6]])

In [7]:
np.reshape(arr,(3,6),'C')

array([[9, 4, 2, 3, 1, 2],
       [6, 4, 4, 4, 1, 5],
       [2, 8, 2, 3, 8, 6]])

In [8]:
np.reshape(arr,(3,6),'F')

array([[9, 4, 2, 3, 1, 2],
       [6, 4, 4, 4, 1, 5],
       [2, 8, 2, 3, 8, 6]])

In [9]:
arr2 = np.random.randint(0,15,(5,3))
arr2

array([[10,  5,  1],
       [14,  8, 11],
       [ 5,  1, 14],
       [14,  6,  4],
       [11,  9, 12]])

In [12]:
np.reshape(arr2,(3,5),'C')

array([[10,  5,  1, 14,  8],
       [11,  5,  1, 14, 14],
       [ 6,  4, 11,  9, 12]])

In [10]:
np.reshape(arr2,(3,5),'F')

array([[10, 14,  8,  9, 14],
       [14, 11,  1,  1,  4],
       [ 5,  5,  6, 11, 12]])

In [11]:
np.reshape(arr2,(3,5),'A')

array([[10,  5,  1, 14,  8],
       [11,  5,  1, 14, 14],
       [ 6,  4, 11,  9, 12]])