In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [13]:
arreglo1 = np.arange(2,22,2)
arreglo1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
arreglocopy = arreglo1.copy()
arreglocopy

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

OPERACIONES

In [15]:
arreglocopy * 2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [16]:
20/arreglocopy

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ])

In [17]:
arreglocopy+arreglo1

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [19]:
matriz = arreglocopy.reshape(2,5)
matriz2 = matriz.copy()
matriz2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [20]:
matriz+matriz2

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])

In [22]:
np.matmul(matriz,matriz2.T)

array([[ 220,  520],
       [ 520, 1320]])

In [30]:
matrizAmergio1 = np.array([[1,-2,-3],[-4,2,1],[5,-1,3]])
matrizAmergio1

array([[ 1, -2, -3],
       [-4,  2,  1],
       [ 5, -1,  3]])

In [34]:
ppunto1 = np.array([1,2,3])
ppunto2 = np.array([4,5,6])

In [35]:
np.matmul(ppunto1,ppunto2)

np.int64(32)

In [36]:
ppunto3 = np.array([-1,2,3])
ppunto4 = np.array([-4,-5,6])

In [37]:
np.matmul(ppunto3,ppunto4)

np.int64(12)

QUIZZ

In [39]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).ndim

2