In [15]:
import pandas as pd
import numpy  as np

In [32]:
lista = [1,2,3,4,5,6,7,8,9,10]

type(lista)

list

In [17]:
arr = np.array(lista) 
type(arr)

numpy.ndarray

In [18]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
(arr[0] + arr[3])*arr[5]

np.int64(30)

In [26]:
matriz[0,2]

np.int64(3)

In [30]:
lista[2:6]

[3, 4, 5, 6]

In [33]:
lista[::3]

[1, 4, 7, 10]

In [34]:
lista[-3]

8

In [40]:
matriz[1:,2]

array([6, 9])

In [48]:
matriz3d = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
matriz3d = np.array(matriz3d)
matriz3d
    

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
matriz3d[0,2,2]

np.int64(9)